server:
  port: 9000
spring:
  application:
    name: messaging-system-server
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  data:
    mongodb:
      repositories:
        type: reactive
com:
  cp:
    projects:
      messaging-system:
        messaging-server:
          security-config:
            jwt-secret: XsuperXsecretXsuperXsecretXsuperXsecretXsuperXsecretXsuperXsecretXsuperXsecretXsuperXsecretXsuperXsecretXsuperXsecretXsuperXsecretX
            allowed-origins:
              - http://localhost:3000
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            exposed-headers:
              - Content-Type
              - Authorization
            allowed-headers:
              - Content-Type
              - Authorization
            allow-credentials: true
        mongo-config:
          username: username
          password: password
          host-uri: localhost
          port: 27017
          auth-source: admin
          database-name: messaging-system-db
        reporting:
          excluded-paths:
            - /actuator/health