spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
    banner-mode: off
  application:
    name: cp-messaging-system-desktop-app
com:
  cp:
    projects:
      messaging-system:
        ui-desktop-app:
          meta:
            application-title: CP Messaging