spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
    banner-mode: off
  application:
    name: cp-messaging-system-desktop-app
com:
  cp:
    projects:
      messaging-system:
        ui-desktop-app:
          meta:
            application-title: CP Messaging
        reactive-clients:
          cp-messaging-auth-server-app:
            base-uri: http://localhost:9900
          cp-messaging-controller-app:
            base-uri: http://localhost:9000
            base-uri-ws: ws://localhost:9000